version: '3'
services:
  db:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: haeun0987
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: Gamsung
    volumes:
      - ./data:/docker-entrypoint-initdb.d
